name: .NET Core CI Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build
      run: dotnet build --configuration Release src/TelloCommander.sln
    - name: Run unit tests and generate code coverage
      run: dotnet test src/TelloCommander.sln /p:CoverletOutput=src/coverage/ /p:CoverletOutputFormat=lcov
    - name: Generage Coveralls code coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: src/coverage/coverage.info 
